local M = {}

M.config = function()
  -- local colors = require("user.theme").colors.gruvchad
  local colors = require("user.theme").colors.gruvbox
  -- custom folder icon
  require("nvim-web-devicons").set_default_icon("", "#6d8086")

  require("nvim-web-devicons").set_icon {
    ["angular.json"] = {
      icon = "",
      -- color = "#D3483E",
      color = colors.red,
      name = "Angular",
    },
    ["angular-cli.json"] = {
      icon = "",
      -- color = "#D3483E",
      color = colors.red,
      name = "Angular",
    },
    [".angular-cli.json"] = {
      icon = "",
      -- color = "#D3483E",
      color = colors.red,
      name = "Angular",
    },
    [".babelrc"] = {
      icon = "",
      -- color = "#FABD2F",
      color = colors.yellow,
      name = "Babel",
    },
    [".babelrc.js"] = {
      icon = "",
      -- color = "#FABD2F",
      color = colors.yellow,
      name = "Babel",
    },
    [".babelrc.json"] = {
      icon = "",
      -- color = "#FABD2F",
      color = colors.yellow,
      name = "Babel",
    },
    [".babel.config.js"] = {
      icon = "",
      -- color = "#FABD2F",
      color = colors.yellow,
      name = "Babel",
    },
    [".babel.config.json"] = {
      icon = "",
      -- color = "#FABD2F",
      color = colors.yellow,
      name = "Babel",
    },
    c = {
      icon = "",
      -- color = "#3276B8",
      color = colors.blue,
      name = "C",
    },
    cc = {
      -- icon = "",
      icon = "",
      -- color = "#3276B8",
      color = colors.blue,
      name = "Cpp",
    },
    cp = {
      -- icon = "",
      icon = "",
      -- color = "#3276B8",
      color = colors.blue,
      name = "Cpp",
    },
    cpp = {
      -- icon = "",
      icon = "",
      -- color = "#3276B8",
      color = colors.blue,
      name = "Cpp",
    },
    cs = {
      -- icon = "",
      icon = "",
      -- color = "#3276B8",
      color = colors.blue,
      name = "CSharp",
    },
    csv = {
      icon = "",
      color = colors.green,
      name = "Csv",
    },
    ["Cargo.lock"] = {
      -- icon = "",
      icon = "",
      -- color = "#FFD54F",
      color = colors.red,
      name = "Lock",
    },
    clj = {
      icon = "",
      -- color = "#cbcb41",
      color = colors.green,
      name = "Clojure",
    },
    cljs = {
      icon = "",
      -- color = "#cbcb41",
      color = colors.green,
      name = "ClojureJS",
    },
    conf = {
      icon = "",
      color = "#6d8086",
      -- color = colors.light_grey,
      name = "Conf",
    },
    css = {
      -- turn off nonicons to use this
      -- icon = "",
      icon = "",
      --   icon = "",
      --   color = "#D3869B",
      -- color = "#42A5F5",
      color = colors.blue,
      name = "Css",
    },
    dart = {
      icon = "",
      -- color = "#03589C",
      color = colors.nord_blue,
      name = "Dart",
    },
    db = {
      icon = "",
      -- color = "#dad8d8",
      color = colors.white,
      name = "Db",
    },
    ["docker-compose.yaml"] = {
      -- icon = "",
      icon = "",
      -- color = "#0187C9",
      color = colors.cyan,
      name = "Dockerfile",
    },
    ["docker-compose.yml"] = {
      -- icon = "",
      icon = "",
      -- color = "#0187C9",
      color = colors.cyan,
      name = "Dockerfile",
    },
    Dockerfile = {
      -- icon = "",
      icon = "",
      -- color = "#0187C9",
      color = colors.cyan,
      name = "Dockerfile",
    },
    dockerfile = {
      -- icon = "",
      icon = "",
      -- color = "#0187C9",
      color = colors.cyan,
      name = "Dockerfile",
    },
    dockerignore = {
      -- icon = "",
      icon = "",
      -- color = "#0187C9",
      color = colors.cyan,
      name = "Dockerfile",
    },
    [".eslintrc.json"] = {
      -- icon = "",
      icon = "",
      -- color = "#7986CB",
      color = colors.purple,
      name = "Eslint",
    },
    [".eslintrc.js"] = {
      -- icon = "",
      icon = "",
      -- color = "#7986CB",
      color = colors.purple,
      name = "Eslint",
    },
    [".eslintrc.yml"] = {
      -- icon = "",
      icon = "",
      -- color = "#7986CB",
      color = colors.purple,
      name = "Eslint",
    },
    [".firebaserc"] = {
      icon = "",
      -- color = "#FBC02D",
      color = colors.sun,
      name = "Firebase",
    },
    ["firebase.json"] = {
      icon = "",
      -- color = "#FBC02D",
      color = colors.sun,
      name = "Firebase",
    },

    -- [".gitignore"] = {
    --   icon = "",
    --   color = "#E64A19",
    --   name = "GitIgnore",
    -- },
    ["git"] = {
      icon = "",
      -- color = "#F14C28",
      color = colors.orange,
      name = "Git",
    },
    [".gitattributes"] = {
      icon = "",
      -- color = "#41535b",
      color = colors.orange,
      name = "GitGray",
    },
    [".gitconfig"] = {
      icon = "",
      -- color = "#41535b",
      color = colors.orange,
      name = "GitGray",
    },
    [".gitignore"] = {
      icon = "",
      -- color = "#41535b",
      color = colors.orange,
      name = "GitGray",
    },
    go = {
      -- icon = "",
      icon = "",
      -- color = "#4BA9BD",
      color = colors.teal,
      name = "Go",
    },
    ["go.mod"] = {
      -- icon = "",
      icon = "",
      -- color = "#DA4F7A",
      color = colors.baby_pink,
      name = "GoMod",
    },
    ["go.sum"] = {
      -- icon = "",
      icon = "",
      -- color = "#DA4F7A",
      color = colors.baby_pink,
      name = "GoMod",
    },
    gql = {
      -- icon = "",
      icon = "",
      -- color = "#D74E78",
      color = colors.baby_pink,
      name = "GraphQL",
    },
    graphql = {
      -- icon = "",
      icon = "",
      -- color = "#D74E78",
      color = colors.baby_pink,
      name = "GraphQL",
    },
    htm = {
      -- turn off nonicons to use this
      -- icon = "",
      icon = "",
      -- color = "#E44D26",
      color = colors.baby_pink,
      name = "Html",
    },
    html = {
      -- turn off nonicons to use this
      -- icon = "",
      icon = "",
      -- color = "#E44D26",
      color = colors.baby_pink,
      name = "Html",
    },
    ico = {
      icon = "",
      -- color = "#cbcb41",
      color = colors.vibrant_green,
      name = "Ico",
    },
    java = {
      icon = "",
      -- color = "#cc3e44",
      color = colors.red,
      name = "Java",
    },
    jpeg = {
      icon = "",
      -- color = "#a074c4",
      color = colors.dark_purple,
      name = "Jpeg",
    },
    jpg = {
      icon = "",
      -- color = "#a074c4",
      color = colors.dark_purple,
      name = "Jpg",
    },
    js = {
      -- icon = "",
      icon = "",
      -- icon = "",
      -- icon = "",
      -- color = "#FABD2F",
      color = colors.sun,
      name = "JavaScript",
    },
    jsx = {
      icon = "",
      -- color = "#519aba",
      color = colors.nord_blue,
      name = "React",
    },
    json = {
      -- icon = "",
      icon = "",
      -- color = "#E1AD2D",
      color = colors.yellow,
      name = "Json",
    },
    kt = {
      -- icon = "",
      icon = "",
      -- color = "#E08C3D",
      color = colors.orange,
      name = "Kotlin",
    },
    license = {
      icon = "",
      -- color = "#cbcb41",
      color = colors.green,
      name = "License",
    },
    ["LICENSE"] = {
      icon = "",
      -- color = "#d0bf41",
      color = colors.green,
      name = "License",
    },
    lua = {
      -- icon = "",
      icon = "",
      -- color = "#51a0cf",
      color = colors.blue,
      name = "Lua",
    },
    [".luacheckrc"] = {
      -- icon = "",
      icon = "",
      -- color = "#51a0cf",
      color = colors.blue,
      name = "Lua",
    },
    md = {
      icon = "",
      -- color = "#42A5F5",
      color = colors.blue,
      name = "Markdown",
    },
    mdx = {
      icon = "",
      -- color = "#42A5F5",
      color = colors.blue,
      name = "Markdown",
    },
    markdown = {
      icon = "",
      -- color = "#42A5F5",
      color = colors.blue,
      name = "Markdown",
    },
    [".markdownlint.json"] = {
      icon = "",
      -- color = "#42A5F5",
      color = colors.blue,
      name = "MarkdownLint",
    },
    ["next.config.js"] = {
      icon = "",
      -- color = "#D0D8DB",
      color = colors.light_grey,
      name = "Next",
    },
    ["next.config.ts"] = {
      icon = "",
      -- color = "#D0D8DB",
      color = colors.light_grey,
      name = "Next",
    },
    ["node_modules"] = {
      icon = "",
      -- color = "#E8274B",
      color = colors.red,
      name = "NPM",
    },
    [".npmignore"] = {
      icon = "",
      -- color = "#E8274B",
      color = colors.red,
      name = "NPM",
    },
    org = {
      icon = "",
      -- color = "#7EAE44",
      color = colors.vibrant_green,
      name = "Org",
    },
    ["package.json"] = {
      -- icon = "",
      icon = "",
      -- color = "#7EAE44",
      color = colors.vibrant_green,
      name = "Node",
    },
    ["package-lock.json"] = {
      -- icon = "",
      icon = "",
      -- color = "#7EAE44",
      color = colors.vibrant_green,
      name = "Node",
    },
    php = {
      icon = "",
      -- color = "#a074c4",
      color = colors.purple,
      name = "Php",
    },
    pl = {
      icon = "",
      -- color = "#519aba",
      color = colors.cyan,
      name = "Pl",
    },
    png = {
      icon = "",
      -- color = "#a074c4",
      color = colors.dark_purple,
      name = "Jpg",
    },
    [".prettierrc.json"] = {
      -- icon = "",
      icon = "",
      -- color = "#6EB1B3",
      color = colors.teal,
      name = "Prettier",
    },
    [".prettierrc.js"] = {
      -- icon = "",
      icon = "",
      -- color = "#6EB1B3",
      color = colors.teal,
      name = "Prettier",
    },
    [".prettierrc.yml"] = {
      -- icon = "",
      icon = "",
      -- color = "#6EB1B3",
      color = colors.teal,
      name = "Prettier",
    },
    py = {
      -- icon = "",
      -- color = "#4B78A6",
      icon = "",
      -- color = "#3572A5",
      color = colors.cyan,
      name = "Python",
    },
    pyc = {
      -- icon = "",
      -- color = "#4B78A6",
      icon = "",
      -- color = "#519aba",
      color = colors.cyan,
      name = "Python",
    },
    pyd = {
      -- icon = "",
      -- color = "#4B78A6",
      icon = "",
      -- color = "#519aba",
      color = colors.cyan,
      name = "Python",
    },
    pyo = {
      -- icon = "",
      -- color = "#4B78A6",
      icon = "",
      -- color = "#519aba",
      color = colors.cyan,
      name = "Python",
    },
    ["requirements.txt"] = {
      icon = "",
      -- icon = "",
      -- color = "#FABD2F",
      color = colors.yellow,
      name = "PyPi",
    },
    ["Pipfile"] = {
      icon = "",
      -- icon = "",
      -- color = "#FABD2F",
      color = colors.yellow,
      name = "PyPi",
    },
    ["pylintrc"] = {
      -- icon = "",
      icon = "",
      -- color = "#519aba",
      color = colors.cyan,
      name = "PythonConfig",
    },
    [".pylintrc"] = {
      -- icon = "",
      icon = "",
      -- color = "#519aba",
      color = colors.cyan,
      name = "PythonConfig",
    },
    r = {
      icon = "",
      -- color = "#358a5b",
      color = colors.vibrant_green,
      name = "R",
    },
    ["rake"] = {
      icon = "",
      -- color = "#701516",
      color = colors.pink,
      name = "Rake",
    },
    ["rakefile"] = {
      icon = "",
      -- color = "#701516",
      color = colors.pink,
      name = "Rakefile",
    },
    ["Gemfile$"] = {
      icon = "",
      -- color = "#701516",
      color = colors.pink,
      name = "Gemfile",
    },
    rb = {
      -- icon = "",
      -- color = "#F44336",
      icon = "",
      -- color = "#701516",
      color = colors.pink,
      name = "rb",
    },
    ["robots.txt"] = {
      -- icon = "ﮧ",
      icon = "",
      -- color = "#FF5252",
      color = colors.red,
      name = "Robots",
    },
    rs = {
      -- icon = "",
      icon = "",
      -- color = "#d28445",
      color = colors.orange,
      name = "Rust",
    },
    scala = {
      icon = "",
      -- color = "#cc3e44",
      color = colors.red,
      name = "Scala",
    },
    sol = {
      icon = "",
      -- color = "#458588",
      -- color = "#A661AB",
      -- color = "#0288D1",
      color = colors.cyan,
      name = "Solidity",
    },
    sql = {
      icon = "",
      -- color = "#dad8d8",
      color = colors.light_grey,
      name = "Sql",
    },
    [".stylelintrc.json"] = {
      icon = "",
      -- color = "#ebdbb2",
      color = colors.white,
      name = "Stylelint",
    },
    [".stylelintrc.js"] = {
      icon = "",
      -- color = "#ebdbb2",
      color = colors.white,
      name = "Stylelint",
    },
    [".stylelintrc.yml"] = {
      icon = "",
      -- color = "#ebdbb2",
      color = colors.white,
      name = "Stylelint",
    },
    svelte = {
      -- icon = "",
      icon = "",
      -- icon = "",
      -- color = "#EC6237",
      color = colors.orange,
      name = "Svelte",
    },
    svg = {
      icon = "",
      -- color = "#F4B53F",
      color = colors.yellow,
      name = "Svg",
    },
    -- svgz = {
    --   icon = "",
    --   color = "#F4B53F",
    --   name = "Svg",
    -- },
    swift = {
      -- icon = "",
      icon = "",
      -- color = "#FE5E2F",
      color = colors.orange,
      name = "Swift",
    },
    ["tailwind.config.js"] = {
      icon = "",
      -- color = "#6AB4AC",
      color = colors.teal,
      name = "Tailwindcss",
    },
    [".tmux.conf"] = {
      -- icon = "",
      icon = "",
      -- color = "#57B53E",
      color = colors.vibrant_green,
      name = "Tmux",
    },
    toml = {
      -- icon = "",
      icon = "",
      -- color = "#FF5252",
      color = colors.red,
      name = "Toml",
    },
    ["truffle-config.js"] = {
      icon = "",
      -- color = "#73DDC6",
      color = colors.cyan,
      name = "Truffle",
    },
    ts = {
      -- icon = "",
      icon = "",
      -- icon = "ﯤ",
      -- icon = "ﯤ",
      -- color = "#3A87CB",
      color = colors.teal,
      name = "TypeScript",
    },
    tsx = {
      icon = "",
      -- color = "#3A87CB",
      -- color = "#519aba",
      color = colors.nord_blue,
      name = "TypeScriptReact",
    },
    txt = {
      icon = "",
      color = colors.light_grey,
      name = "Txt",
    },
    vim = {
      icon = "",
      -- color = "#7EAE44",
      color = colors.vibrant_green,
      name = "Vim",
    },
    [".gvimrc"] = {
      icon = "",
      -- color = "#019833",
      color = colors.vibrant_green,
      name = "Vim",
    },
    [".vimrc"] = {
      icon = "",
      -- color = "#019833",
      color = colors.vibrant_green,
      name = "Vim",
    },
    vue = {
      -- icon = "﵂",
      icon = "",
      -- color = "#64B587",
      color = colors.vibrant_green,
      name = "Vue",
    },
    ["webpack"] = {
      icon = "",
      -- icon = "",
      -- color = "#9FD3F3",
      color = colors.nord_blue,
      name = "Webpack",
    },
    ["webpack.js"] = {
      icon = "",
      -- icon = "",
      -- color = "#9FD3F3",
      color = colors.nord_blue,
      name = "Webpack",
    },
    ["webpack.config"] = {
      icon = "",
      -- icon = "",
      -- color = "#9FD3F3",
      color = colors.nord_blue,
      name = "Webpack",
    },
    xz = {
      -- icon = "",
      icon = "",
      -- color = "#AFB42B",
      color = colors.green,
      name = "Zip",
    },
    zip = {
      -- icon = "",
      icon = "",
      -- color = "#AFB42B",
      color = colors.green,
      name = "Zip",
    },
    ["yarn.lock"] = {
      -- icon = "",
      icon = "",
      -- color = "#42A5F5",
      color = colors.blue,
      name = "Yarn",
    },
    yml = {
      -- icon = "",
      icon = "",
      -- color = "#FF5252",
      color = colors.red,
      name = "Yaml",
    },
    yaml = {
      -- icon = "",
      icon = "",
      -- color = "#FF5252",
      color = colors.red,
      name = "Yaml",
    },
    zsh = {
      -- icon = "",
      icon = "",
      -- icon = "",
      -- color = "#FF7043",
      color = colors.orange,
      name = "Zsh",
    },
    [".zshrc"] = {
      -- icon = "",
      icon = "",
      -- icon = "",
      -- color = "#FF7043",
      color = colors.orange,
      name = "Zsh",
    },
    [".zshenv"] = {
      -- icon = "",
      icon = "",
      -- icon = "",
      -- color = "#FF7043",
      color = colors.orange,
      name = "Zsh",
    },
    [".zprofile"] = {
      -- icon = "",
      icon = "",
      -- icon = "",
      -- color = "#FF7043",
      color = colors.orange,
      name = "Zsh",
    },
    bash = {
      -- icon = "",
      icon = "",
      -- icon = "",
      -- color = "#FF7043",
      color = colors.orange,
      name = "Zsh",
    },
    sh = {
      -- icon = "",
      icon = "",
      -- icon = "",
      -- color = "#FF7043",
      color = colors.orange,
      name = "Sh",
    },

    -- hy = {
    --   icon = "",
    --   color = "#D9B06F",
    --   name = "Hy",
    -- },
    -- TODO: a lot more of these for webpack
    -- vy = {
    --   icon = "",
    --   color = "#0288D1",
    --   name = "Vyper",
    -- },
    -- deb = {
    --   icon = "",
    --   color = "#9A1E33",
    --   name = "deb",
    -- },
    -- TODO: maybe someday devicon will have support for regexes in filename
    -- ["*.test.js"] = {
    --   icon = "ﭧ",
    --   color = "#cbcb41",
    --   name = "JavascriptTest",
    -- },
  }
end

return M
