vim.cmd "set nospell"
-- TODO markdown formatting and linting not working
-- lvim.lang.markdown.formatters = {
--   {
--     exe = "prettier",
--     args = {},
--   },
-- }
-- lvim.lang.markdown.linters = {
--   {
--     -- TODO install vale (copy from abzcoding/lvim)
--     -- @usage can be write_good or vale or markdownlint
--     -- exe = "vale",
--     exe = "",
--     args = {},
--   },
--   {
--     exe = "markdownlint",
--     args = {},
--   },
-- }
